In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\hugom\projetos\predicao_cardiaco\data\raw\heart_disease_uci.csv")
df

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
916,917,62,Male,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
917,918,55,Male,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,NaN,fixed defect,2
918,919,58,Male,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
919,920,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [3]:
df.describe()

,id,age,trestbps,chol,thalch,oldpeak,ca,num
count,920.000000,920.000000,861.000000,890.000000,865.000000,858.000000,309.000000,920.000000
mean,460.500000,53.510870,132.132404,199.130337,137.545665,0.878788,0.676375,0.995652
std,265.725422,9.424685,19.066070,110.780810,25.926276,1.091226,0.935653,1.142693
min,1.000000,28.000000,0.000000,0.000000,60.000000,-2.600000,0.000000,0.000000
25%,230.750000,47.000000,120.000000,175.000000,120.000000,0.000000,0.000000,0.000000
50%,460.500000,54.000000,130.000000,223.000000,140.000000,0.500000,0.000000,1.000000
75%,690.250000,60.000000,140.000000,268.000000,157.000000,1.500000,1.000000,2.000000
max,920.000000,77.000000,200.000000,603.000000,202.000000,6.200000,3.000000,4.000000

In [4]:
df.columns

Index(['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

In [5]:
df.drop("dataset", axis=1, inplace=True)

In [6]:
df.columns

Index(['id', 'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

In [7]:
df.shape

(920, 15)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    object
 3   cp        920 non-null    object
 4   trestbps  861 non-null    float64
 5   chol      890 non-null    float64
 6   fbs       830 non-null    object
 7   restecg   918 non-null    object
 8   thalch    865 non-null    float64
 9   exang     865 non-null    object
 10  oldpeak   858 non-null    float64
 11  slope     611 non-null    object
 12  ca        309 non-null    float64
 13  thal      434 non-null    object
 14  num       920 non-null    int64
dtypes: float64(5), int64(3), object(7)
memory usage: 107.9+ KB

In [9]:
df.isnull().sum()

id            0
age           0
sex           0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df_sem = df.copy()

In [12]:
df_sem.drop(columns=['ca'], inplace=True)

In [13]:
df_sem.columns

Index(['id', 'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'thal', 'num'],
      dtype='object')

In [14]:
df.columns

Index(['id', 'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

In [15]:
df_sem["thal"] = df_sem.groupby(["cp", "sex"])["thal"].transform(lambda x: x.fillna(x.mode()[0]))
#faz o imput nos valores faltantes de thal de acordo com o grupo cp e sex

In [16]:
df_sem.isnull().sum()

id            0
age           0
sex           0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
thal          0
num           0
dtype: int64

In [17]:
df_sem['slope'] = df_sem.groupby(["cp", "sex"])["slope"].transform(lambda x: x.fillna(x.mode()[0]))

In [18]:
df_sem.isnull().sum()

id           0
age          0
sex          0
cp           0
trestbps    59
chol        30
fbs         90
restecg      2
thalch      55
exang       55
oldpeak     62
slope        0
thal         0
num          0
dtype: int64

In [19]:
df_sem['trestbps'] = df_sem.groupby(["cp", "sex"])["trestbps"].transform(lambda x: x.fillna(x.median()))
df_sem.isnull().sum()

id           0
age          0
sex          0
cp           0
trestbps     0
chol        30
fbs         90
restecg      2
thalch      55
exang       55
oldpeak     62
slope        0
thal         0
num          0
dtype: int64

In [20]:
df_sem['chol'] = df_sem.groupby(["cp", "sex"])["chol"].transform(lambda x: x.fillna(x.median()))
df_sem.isnull().sum()

id           0
age          0
sex          0
cp           0
trestbps     0
chol         0
fbs         90
restecg      2
thalch      55
exang       55
oldpeak     62
slope        0
thal         0
num          0
dtype: int64

In [21]:
df_sem['fbs'] = df_sem.groupby(["cp", "sex"])["fbs"].transform(lambda x: x.fillna(x.mode()[0]))
df_sem.isnull().sum()

C:\Users\hugonobrega\AppData\Local\Temp\ipykernel_16624\1875338508.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_sem['fbs'] = df_sem.groupby(["cp", "sex"])["fbs"].transform(lambda x: x.fillna(x.mode()[0]))

id           0
age          0
sex          0
cp           0
trestbps     0
chol         0
fbs          0
restecg      2
thalch      55
exang       55
oldpeak     62
slope        0
thal         0
num          0
dtype: int64

In [22]:
df_sem['restecg'] = df_sem.groupby(["cp", "sex"])["restecg"].transform(lambda x: x.fillna(x.mode()[0]))
df_sem.isnull().sum()

id           0
age          0
sex          0
cp           0
trestbps     0
chol         0
fbs          0
restecg      0
thalch      55
exang       55
oldpeak     62
slope        0
thal         0
num          0
dtype: int64

In [23]:
df_sem['thalch'] = df_sem.groupby(["cp", "sex"])["thalch"].transform(lambda x: x.fillna(x.median()))
df_sem.isnull().sum()

id           0
age          0
sex          0
cp           0
trestbps     0
chol         0
fbs          0
restecg      0
thalch       0
exang       55
oldpeak     62
slope        0
thal         0
num          0
dtype: int64

In [24]:
df_sem['exang'] = df_sem.groupby(["cp", "sex"])["exang"].transform(lambda x: x.fillna(x.mode()[0]))
df_sem.isnull().sum()

C:\Users\hugonobrega\AppData\Local\Temp\ipykernel_16624\1256624273.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_sem['exang'] = df_sem.groupby(["cp", "sex"])["exang"].transform(lambda x: x.fillna(x.mode()[0]))

id           0
age          0
sex          0
cp           0
trestbps     0
chol         0
fbs          0
restecg      0
thalch       0
exang        0
oldpeak     62
slope        0
thal         0
num          0
dtype: int64

In [25]:
df_sem['oldpeak'] = df_sem.groupby(["cp", "sex"])["oldpeak"].transform(lambda x: x.fillna(x.median()))
df_sem.isnull().sum()

id          0
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
thal        0
num         0
dtype: int64

In [26]:
#binarizando a coluna "num"
df_sem["target"] = (df_sem["num"] > 0).astype(int)
print(df_sem["target"].value_counts())

target
1    509
0    411
Name: count, dtype: int64

In [27]:
df_sem = df_sem.drop(columns = ["num"])
df_sem

,id,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,thal,target
0,1,63,Male,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,fixed defect,0
1,2,67,Male,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,normal,1
2,3,67,Male,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,reversable defect,1
3,4,37,Male,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,normal,0
4,5,41,Female,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54,Female,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,flat,normal,1
916,917,62,Male,typical angina,136.0,139.0,False,st-t abnormality,150.0,False,1.2,flat,normal,0
917,918,55,Male,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,flat,fixed defect,1
918,919,58,Male,asymptomatic,130.0,385.0,True,lv hypertrophy,126.0,True,1.0,flat,reversable defect,0
919,920,62,Male,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,upsloping,normal,1

In [28]:
df_sem.to_csv(r'C:\Users\hugonobrega\predicao_cardiaco\data\processed\processed_without_ca.csv', index=False)